server:  
  port: ${PORT:8080}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/}

spring: 
  application:
    name: sample-service
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:169.56.100.104}:${DB_PORT:32350}/${DB_NAME:demo}?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME:user00}
    password: ${DB_PASSWORD:admin1234}
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1    

#MyBatis
mybatis:
    mapper-locations: classpath:mybatis/mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true  

garage:
  product:
    server: ${PRODUCT_SERVER:169.56.100.110}
    port: ${PRODUCT_PORT:8081}
