server:  
  port: ${PORT:8888}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/nexthouse}

spring: 
  application:
    name: nexthouse
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:169.56.100.104}:${DB_PORT:31587}/${DB_NAME:nexthouse}?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:960328}
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1

#MyBatis
mybatis:
    mapper-locations: classpath:mybatis/mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true  

garage:
  product:
    server: ${PRODUCT_SERVER:169.56.100.110}
    port: ${PRODUCT_PORT:8081}
